client/app/app.js
client/app/controllers.js
client/app/services.js
client/templates/query_profile_grid.html

depends on PRs: [pmm-proto](https://github.com/percona/pmm/pull/2) & [qan-api](https://github.com/percona/qan-api/pull/1)

[PPL-75] Added total row for at begining of top queries.

---

proxy.conf.json
src/app/query-profile/query-profile.component.html

Change config to launch app
Remove unnecessary links

[PMM-1829] Remove unnecessary links

---

src/app/query-profile/query-profile.component.html
src/styles.scss

related with  https://github.com/percona/qan-api/pull/41

[PMM-1777] Fixed sparklines for Load. Added description for Load.

---

src/app/mysql-query-details/mysql-query-details.component.html

https://jira.percona.com/browse/PMM-1893

PMM-1893 Fix bootstrap class for table elements

---

src/app/summary/summary.component.ts
src/app/summary/summary.service.ts

[PMM-605](https://jira.percona.com/browse/PMM-605)
https://github.com/percona/qan-api/pull/28
Will that do the trick? It's a similar change to https://github.com/percona/qan-app/commit/3d4f345998e7c5080e6452290d809ed1cd48796e
I didn't test that, so please verify.

PMM-605: Use new query.Summary service.

---

src/app/mongo-query-details/mongo-query-details.component.ts
src/app/mysql-query-details/mysql-query-details.component.html

https://jira.percona.com/browse/PMM-2171

[PMM-2171] Fix displaying json section

---

src/app/mysql-query-details/mysql-query-details.component.ts

Just show error message when https://github.com/percona/go-mysql/blob/master/event/class.go#L25 is reached. Please test & verify as I'm not familiar with qan-app.

PMM-2176 Temporary hack for max example size.

---

src/app/add-aws/add-aws.component.html

https://jira.percona.com/browse/PMM-1788

[PMM-1788] AWS Credentials form changes

---

.editorconfig
src/app/mongo-query-details/mongo-query-details.component.html
src/app/mongo-query-details/mongo-query-details.component.scss
src/app/mysql-query-details/mysql-query-details.component.html
src/app/mysql-query-details/mysql-query-details.component.scss

https://jira.percona.com/browse/PMM-2311

PMM-2311 metric table

---

src/app/mysql-query-details/mysql-query-details.component.html
src/app/mysql-query-details/mysql-query-details.component.ts

https://jira.percona.com/browse/PMM-2362

PMM-2362 Fix query explain

---

src/app/mongo-query-details/mongo-query-details.component.html
src/app/mysql-query-details/mysql-query-details.component.html

https://jira.percona.com/browse/PMM-2388

PMM-2388 Fix rendering query fingerprint

---

src/app/mysql-query-details/mysql-query-details.component.ts

https://jira.percona.com/browse/PMM-2362?focusedCommentId=225290&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-225290

PMM-2362 Fix displaying example part

---

src/app/settings/settings.component.html

https://jira.percona.com/browse/PMM-2436

PMM-2436 Add new options

---

package-lock.json
package.json

https://jira.percona.com/browse/PMM-2966

PMM-2966 Update dependency

---

package-lock.json

https://jira.percona.com/browse/PMM-3413

PMM-3413 Fix vulnerability

---

package-lock.json

https://jira.percona.com/browse/PMM-4139

PMM-4139 Update fstream

---

package-lock.json

https://jira.percona.com/browse/PMM-4337

PMM-2.0 Update lodash

---

package-lock.json

https://jira.percona.com/browse/PMM-4337

PMM-2.0 Update lodash.mergewith version

---

package.json
src/app/qan/profile-details/components/details-table/details-table.component.ts
src/app/qan/profile-details/components/examples-viewer/examples-viewer.component.html
src/app/qan/profile-details/components/query-example/query-example.component.css
src/app/qan/profile-details/components/query-example/query-example.component.html
src/app/qan/profile-details/components/query-example/query-example.component.ts

feat: added JSON formatting
fix: added words wrap in examples output

PMM-4545 query example view improvements

---

src/app/qan/filter-menu-viewer/filter-menu-viewer.component.html
src/app/qan/filter-menu/filter-menu.component.html
src/app/qan/filter-menu/filter-menu.component.scss
src/app/qan/filter-menu/filter-menu.component.ts
src/app/qan/profile-details/components/details-labels/details-labels.component.html

https://jira.percona.com/browse/PMM-4063
Before:
Now:

PMM-4063 Checkbox -> li in object details label list.

---

src/app/global-styles/checkbox.scss
src/app/qan/filter-menu/filter-menu.component.html

https://jira.percona.com/browse/PMM-4988
Related PRs:
- https://github.com/percona/qan-api2/pull/69
FB:
- https://github.com/Percona-Lab/pmm-submodules/pull/535

PMM-4988 Filter improvement.

---

src/app/qan/filter-menu/filter-groups-list.ts

https://github.com/Percona-Lab/pmm-submodules/pull/578

PMM-5140: add container id humanization

---

src/app/qan/filter-menu/filter-menu.component.html
src/app/qan/search-autocomplete/search-autocomplete.component.html

FB: https://github.com/Percona-Lab/pmm-submodules/pull/624 
Tasks PMM-5131 and PMM-5127

PMM-5131: display improvements

---

package.json
src/app/qan/profile-table/profile-table.component.ts

https://github.com/Percona-Lab/pmm-submodules/pull/628

PMM-5060: missing rows fix

---

src/app/qan/profile-table/profile-table.component.ts

https://github.com/Percona-Lab/pmm-submodules/pull/663

PMM-5378: total rows return

---

src/app/qan/profile-details/components/query-example/query-example.component.ts

PMM-5178: add show create table display

---

package.json
src/app/core/services/query-params.service.ts
src/app/qan/profile-details/components/details-table/details-table.component.ts
src/app/qan/profile-table/profile-table.component.html

FB: https://github.com/Percona-Lab/pmm-submodules/pull/736

PMM-5528: filtering by total

---

package-lock.json
src/app/core/services/query-params.service.ts
src/app/qan/table-cell/table-cell.component.html

PMM-5555: move units to tooltip
